---
#playbook para testes conditional

- name: exemplo  de operador de condicional
  hosts: all


  tasks:
   - name: teste o arquivo profile
     command: test -f /etc/profile.d/dexter
     register: result
     ignore_errors: yes

   - name: criando o arquivo
     file: 
      path: /etc/profile.d/dexter
      owner: root
      group: root
      mode: 0644
      state: touch
     when: result.rc != 0


   - name: configurando a variavel da dexter
     shell: echo "export DEXTER=/opt/dexter" > /etc/profile.d/dexter
     when: result.rc == 0
