---
# Playbook de criacao de usuarios

- name: cria logins
  hosts: all
  tasks:
   - name: criando logins
     user:
      name: "{{ item }}"
      shell: /bin/bash
      createhome: yes
     with_items:
      - devops
      - eder
      - developer
      - 4linux


   - name: instalacao pacotes apt
     apt:
      name: "{{ item }}"
      state: present
     with_items:
      - vim 
      - nano 
      - sl 
      - ccze 
      - dnsutils 
     ignore_errors: yes

   - name: instalacao pacotes yum
     yum:
      name: "{{ item }}"
      state: present
     with_items:
      - vim 
      - nano 
      - sl 
      - ccze 
      - bind-utils 
      - epel-release
     ignore_errors: yes
